# Generated by Django 5.1.7 on 2025-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
