services:
  - type: web
    name: Course-App-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn deutsch_kurs.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: deutsch_kurs.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
